const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='farjan_final_state';
const defaults={profile:null,points:0,sessions:[],plan:{game:'balance',rounds:5,hold:3,note:''},settings:{voice:true}};
let state=load();
let activeGame='balance',camera=null,pose=null,cameraActive=false,paused=false,demoMode=false,holdStart=null,roundLocked=false,rounds=0,score=0,startTime=0,timer=null,lastResultId=null,selectedRating=0;
let speechSet='sea',speechIndex=0,speechCorrect=0,speechScores=[];
const GAMES={balance:{title:'الحجلة الخليجية',type:'التوازن',icon:'⚖️',mission:'ارفع قدمًا واحدة',desc:'حافظ على توازنك لمدة {hold} ثوانٍ.',rounds:5,hold:3,m1:'زاوية الركبة اليسرى',m2:'زاوية الركبة اليمنى'},pearl:{title:'جمع اللؤلؤ',type:'الوصول والانحناء',icon:'🦪',mission:'اجمع اللؤلؤ',desc:'انحنِ تدريجيًا ومد يدك للأسفل.',rounds:6,hold:1.2,m1:'متوسط زاوية الركبتين',m2:'اليد للأسفل'},sail:{title:'رفع الشراع',type:'حركة الذراعين',icon:'⛵',mission:'ارفع الشراع',desc:'ارفع كلتا اليدين فوق الكتفين وثبّت الوضعية.',rounds:5,hold:2,m1:'اليد اليسرى فوق الكتف',m2:'اليد اليمنى فوق الكتف'}};
const SPEECH={sea:{title:'كلمات من البحر',words:['لؤلؤ','سفينة','شراع','بحر']},qatar:{title:'كلمات من قطر',words:['راية','نخلة','سوق','فريج']},sounds:{title:'تمييز الأصوات',words:['سمكة','شمس','رمل','قمر']}};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaults,...x,plan:{...defaults.plan,...(x.plan||{})},settings:{...defaults.settings,...(x.settings||{})}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function speak(text){if(!state.settings.voice||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ar-QA';u.rate=.95;u.pitch=1.05;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/^ar/i.test(v.lang))||null;speechSynthesis.speak(u)}catch{}}
function route(n){$$('.page').forEach(p=>p.classList.remove('active'));const p=$('#page-'+n);if(!p)return;p.classList.add('active');scrollTo({top:0,behavior:'instant'});if(n==='dashboard')renderDashboard();if(n==='games')renderPoints();if(n==='reports')renderReports();if(n==='therapist')renderTherapist();if(n==='assessment')renderAssessment();syncVoice()}
function bindRoutes(){$$('[data-route]').forEach(b=>b.onclick=()=>{const n=b.dataset.route;if(['dashboard','games','speech','assessment','reports','therapist'].includes(n)&&!state.profile){route('onboarding');toast('أنشئ ملف الطفل أولًا');return}route(n)});$$('[data-scroll]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.scroll)?.scrollIntoView({behavior:'smooth'});$('.topnav')?.classList.remove('open')})}
$('#menuBtn').onclick=()=>$('.topnav').classList.toggle('open');
$('#childForm').onsubmit=e=>{e.preventDefault();state.profile={name:$('#childName').value.trim(),age:$('#childAge').value,goal:$('#childGoal').value,level:$('#childLevel').value,created:new Date().toISOString()};save();route('dashboard');speak('تم إنشاء ملف الطفل، أهلا بك في فرجان الحركية')};
function syncVoice(){const v=state.settings.voice;if($('#voiceToggleBtn'))$('#voiceToggleBtn').textContent=v?'🔊 التعزيز الصوتي: مفعّل':'🔇 التعزيز الصوتي: متوقف';if($('#playVoiceToggleBtn'))$('#playVoiceToggleBtn').textContent=v?'🔊 الصوت مفعّل':'🔇 الصوت متوقف'}
function toggleVoice(){state.settings.voice=!state.settings.voice;save();syncVoice();toast(state.settings.voice?'تم تفعيل الصوت':'تم إيقاف الصوت');if(state.settings.voice)speak('تم تفعيل التعزيز الصوتي')}
$('#voiceToggleBtn').onclick=toggleVoice;$('#playVoiceToggleBtn').onclick=toggleVoice;
function goalLabel(v){return {balance:'تعزيز التوازن',upper:'رفع ومد الذراعين',mobility:'الحركة والوصول',speech:'النطق واللغة',general:'برنامج متكامل'}[v]||'برنامج متكامل'}
function renderPoints(){['dashboardPoints','gamesPoints'].forEach(id=>{if($('#'+id))$('#'+id).textContent=state.points})}
function progress(){const p=Math.min(100,Math.round(state.sessions.length*9+state.points/10));return {p,level:p<35?'المستوى الأول':p<70?'المستوى الثاني':'المستوى الثالث'}}
function renderDashboard(){renderPoints();const p=state.profile||{};$('#welcomeName').textContent=p.name?`مرحبًا ${p.name} 👋`:'مرحبًا 👋';$('#todayMission').textContent=`مهمتك: ${GAMES[state.plan.game]?.title||'جلسة جديدة'}`;$('#sessionCountMini').textContent=state.sessions.length?`${state.sessions.length} جلسة مسجلة`:'لا جلسات بعد';$('#planNoteView').textContent=state.plan.note||'لا توجد ملاحظة محفوظة بعد.';const pr=progress();$('#progressTitle').textContent=pr.level;$('#overallProgressText').textContent=pr.p+'%';$('#overallProgressBar').style.width=pr.p+'%';$('#overallProgressHint').textContent=state.sessions.length?`تم تسجيل ${state.sessions.length} جلسة وجمع ${state.points} نقطة.`:'ابدأ أول جلسة لعرض مستوى التقدم.'}
$$('.game-start').forEach(b=>b.onclick=()=>startGame(b.dataset.game));
function startGame(g){activeGame=g;rounds=0;score=0;holdStart=null;roundLocked=false;demoMode=false;setupPlay();route('play');speak(`سنبدأ الآن لعبة ${GAMES[g].title}`)}
function setupPlay(){const c={...GAMES[activeGame]};if(state.plan.game===activeGame){c.rounds=+state.plan.rounds||c.rounds;c.hold=+state.plan.hold||c.hold}window.cfg=c;$('#playGameType').textContent=c.type;$('#playTitle').textContent=c.title;$('#missionIcon').textContent=c.icon;$('#missionTitle').textContent=c.mission;$('#missionDesc').textContent=c.desc.replace('{hold}',c.hold);$('#holdTargetLabel').textContent=` / ${c.hold.toFixed(1)} ثانية`;$('#roundValue').textContent=`0 / ${c.rounds}`;$('#playScore').textContent='0';$('#metric1Label').textContent=c.m1;$('#metric2Label').textContent=c.m2;$('#metric1').textContent='—';$('#metric2').textContent='—';$('#trackingConfidence').textContent='—';$('#detected').textContent='بانتظار الكاميرا';$('#holdValue').textContent='0.0';$('#holdProgress').style.width='0%';$('#cameraOverlay').classList.remove('hide');$('#simulateSuccessBtn').classList.add('hidden');$('#sessionTimer').textContent='00:00';$('#poseStatus').textContent='● الكاميرا متوقفة';clearInterval(timer)}
function angle(a,b,c){const ab={x:a.x-b.x,y:a.y-b.y},cb={x:c.x-b.x,y:c.y-b.y};const d=Math.hypot(ab.x,ab.y)*Math.hypot(cb.x,cb.y);if(!d)return 180;let co=(ab.x*cb.x+ab.y*cb.y)/d;co=Math.max(-1,Math.min(1,co));return Math.acos(co)*180/Math.PI}
function visible(l){return [0,11,12,23,24,25,26,27,28].every(i=>(l[i].visibility??1)>.45)}
function evalPose(l){let good=false,m1='—',m2='—';if(activeGame==='balance'){const a=angle(l[23],l[25],l[27]),b=angle(l[24],l[26],l[28]);m1=Math.round(a)+'°';m2=Math.round(b)+'°';good=(a<150&&b>158)||(b<150&&a>158)}else if(activeGame==='pearl'){const a=angle(l[23],l[25],l[27]),b=angle(l[24],l[26],l[28]),av=(a+b)/2,w=Math.min(l[15].y,l[16].y),h=(l[23].y+l[24].y)/2;m1=Math.round(av)+'°';m2=w>h?'نعم':'ليس بعد';good=av<145&&w>h}else{const le=l[15].y<l[11].y,ri=l[16].y<l[12].y;m1=le?'نعم ✓':'لا';m2=ri?'نعم ✓':'لا';good=le&&ri}$('#metric1').textContent=m1;$('#metric2').textContent=m2;return good}
function updateHold(g){if(paused)return;const c=window.cfg;if(g){if(!holdStart){holdStart=performance.now();speak('ممتاز، استمر')}const s=Math.min(c.hold,(performance.now()-holdStart)/1000);$('#holdValue').textContent=s.toFixed(1);$('#holdProgress').style.width=(s/c.hold*100)+'%';$('#feedbackBubble').textContent=s<c.hold?'ممتاز، حافظ على الوضع':'أحسنت يا بطل!';if(s>=c.hold&&!roundLocked)scoreRound()}else if(!roundLocked){holdStart=null;$('#holdValue').textContent='0.0';$('#holdProgress').style.width='0%';$('#feedbackBubble').textContent=activeGame==='balance'?'ارفع قدمًا واحدة':activeGame==='pearl'?'انحنِ ومد يدك للأسفل':'ارفع اليدين فوق الكتفين'}}
function scoreRound(){roundLocked=true;rounds++;score+=10;$('#roundValue').textContent=`${rounds} / ${window.cfg.rounds}`;$('#playScore').textContent=score;speak(rounds>=window.cfg.rounds?'رائع، أنهيت التحدي بنجاح':'أحسنت، الجولة التالية');if(rounds>=window.cfg.rounds)setTimeout(()=>finishMovement(false),600);else setTimeout(()=>{holdStart=null;roundLocked=false;$('#holdValue').textContent='0.0';$('#holdProgress').style.width='0%'},850)}
function initPose(){if(pose)return;pose=new Pose({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/pose/${f}`});pose.setOptions({modelComplexity:1,smoothLandmarks:true,minDetectionConfidence:.55,minTrackingConfidence:.55});pose.onResults(r=>{const v=$('#video'),c=$('#canvas'),x=c.getContext('2d');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;x.clearRect(0,0,c.width,c.height);if(r.poseLandmarks){const l=r.poseLandmarks;drawConnectors(x,l,POSE_CONNECTIONS,{color:'#35d0a0',lineWidth:4});drawLandmarks(x,l,{color:'#ffd56a',radius:3});const ok=visible(l);$('#detected').textContent=ok?'كامل ✓':'غير كامل';$('#trackingConfidence').textContent=ok?'جيدة':'ضعيفة';$('#poseStatus').textContent=ok?'● الجسم ظاهر':'● عدّل موقع الكاميرا';if(ok)updateHold(evalPose(l));else{$('#feedbackBubble').textContent='ابتعد قليلًا ليظهر الجسم كاملًا';holdStart=null}}else{$('#detected').textContent='لم يتم الاكتشاف'}})}
function beginTimer(){startTime=Date.now();timer=setInterval(()=>$('#sessionTimer').textContent=fmt(Math.round((Date.now()-startTime)/1000)),1000)}
$('#startCameraBtn').onclick=async()=>{try{initPose();cameraActive=true;$('#cameraOverlay').classList.add('hide');const v=$('#video');camera=new Camera(v,{onFrame:async()=>{if(cameraActive&&!paused)await pose.send({image:v})},width:1280,height:720});await camera.start();beginTimer();speak('قف في المنتصف ليظهر جسمك كاملًا')}catch(e){console.error(e);toast('تعذر تشغيل الكاميرا. امنح إذن الكاميرا أو استخدم المحاكاة.')}};
$('#demoModeBtn').onclick=()=>{demoMode=true;$('#cameraOverlay').classList.add('hide');$('#simulateSuccessBtn').classList.remove('hidden');$('#detected').textContent='محاكاة';$('#trackingConfidence').textContent='تجريبي';beginTimer();speak('تم تشغيل وضع المحاكاة')};
$('#simulateSuccessBtn').onclick=()=>{if(roundLocked)return;holdStart=performance.now()-window.cfg.hold*1000;updateHold(true)};$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'▶ متابعة':'⏸ إيقاف مؤقت';if(!paused)speak('تابع الحركة')};$('#endGameBtn').onclick=()=>{if(confirm('إنهاء الجلسة؟'))finishMovement(true)};
function stopCamera(){cameraActive=false;if(camera){try{camera.stop()}catch{}camera=null}clearInterval(timer)}
function finishMovement(cancelled=false){stopCamera();const dur=startTime?Math.max(1,Math.round((Date.now()-startTime)/1000)):0;if(cancelled&&rounds===0){route('games');return}const rate=Math.round(rounds/window.cfg.rounds*100);const s={id:Date.now(),kind:'movement',activity:window.cfg.title,game:activeGame,date:new Date().toISOString(),duration:dur,completed:rounds,target:window.cfg.rounds,score:rate,points:score,rating:null,note:''};state.sessions.unshift(s);state.points+=score;save();renderResult(s);route('result')}
function fmt(s){s=Math.max(0,+s||0);const m=Math.floor(s/60),r=s%60;return m?`${m}:${String(r).padStart(2,'0')} د`:`${r} ث`}
function renderResult(s){lastResultId=s.id;selectedRating=s.rating||0;$('#resultHeadline').textContent=`أحسنت ${state.profile?.name||''}!`;$('#resultSubtitle').textContent=s.kind==='speech'?'تم حفظ نتيجة تدريب النطق.':'تم حفظ تقدمك في الجلسة الحركية.';$('#resultStats').innerHTML=(s.kind==='speech'?[['🗣️ النوع','نطق'],['🎯 النتيجة',s.score+'%'],['⭐ النقاط','+'+s.points]]:[['🤸 النشاط',s.activity],['🎯 الإنجاز',s.score+'%'],['⭐ النقاط','+'+s.points]]).map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b></article>`).join('');$('#evalNote').value=s.note||'';$$('.rate-btn').forEach(b=>b.classList.toggle('active',+b.dataset.rate===selectedRating));speak('أحسنت، تم حفظ تقدمك')}
$$('.rate-btn').forEach(b=>b.onclick=()=>{selectedRating=+b.dataset.rate;$$('.rate-btn').forEach(x=>x.classList.toggle('active',x===b));speak(['','سنحاول بشكل أبسط في المرة القادمة','بداية طيبة','أداء جيد','ممتاز جدًا','رائع يا بطل'][selectedRating])});
$('#saveEvaluationBtn').onclick=()=>{const i=state.sessions.findIndex(s=>s.id===lastResultId);if(i<0)return;state.sessions[i].rating=selectedRating||null;state.sessions[i].note=$('#evalNote').value.trim();save();$('#evalSaveMsg').textContent='تم حفظ تقييم ولي الأمر.';toast('تم حفظ التقييم')};

// Speech
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function normalizeArabic(s=''){return s.normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[^\u0621-\u064A ]/g,'').trim()}
function lev(a,b){a=normalizeArabic(a);b=normalizeArabic(b);const m=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)m[i][0]=i;for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]}
function similarity(a,b){const aa=normalizeArabic(a),bb=normalizeArabic(b);if(!aa&&!bb)return 100;return Math.max(0,Math.round((1-lev(aa,bb)/Math.max(aa.length,bb.length,1))*100))}
$$('.speech-start').forEach(b=>b.onclick=()=>{speechSet=b.dataset.set;speechIndex=0;speechCorrect=0;speechScores=[];route('speechplay');renderSpeechWord()});
function renderSpeechWord(){const set=SPEECH[speechSet],w=set.words[speechIndex];$('#speechSetTitle').textContent=set.title;$('#speechTarget').textContent=w;$('#speechPrompt').textContent='استمع للكلمة ثم انطقها بوضوح.';$('#heardText').textContent='—';$('#speechScore').textContent='0%';$('#speechScoreRing').style.background='conic-gradient(#159469 0%,#e8ecec 0)';$('#speechFeedback').textContent='جاهز للتجربة';$('#speechFeedbackText').textContent='اضغط «ابدأ النطق» ثم قل الكلمة.';$('#speechRound').textContent=`${speechIndex+1} / ${set.words.length}`;$('#speechProgressBar').style.width=`${(speechIndex+1)/set.words.length*100}%`;$('#nextSpeechBtn').classList.add('hidden')}
$('#listenTargetBtn').onclick=()=>speak($('#speechTarget').textContent);$('#speechVoiceBtn').onclick=()=>speak('أهلا بك في ركن النطق واللغة. سنستمع للكلمة ثم نكررها بوضوح.');
$('#recordSpeechBtn').onclick=()=>{if(!SpeechRecognition){toast('المتصفح لا يدعم التعرف على الكلام. استخدم Chrome أو Edge.');return}const r=new SpeechRecognition();r.lang='ar-QA';r.interimResults=false;r.maxAlternatives=3;$('#recordSpeechBtn').textContent='🎙️ أستمع الآن...';r.onresult=e=>{const heard=e.results[0][0].transcript;const target=$('#speechTarget').textContent;const sc=similarity(heard,target);$('#heardText').textContent=heard;$('#speechScore').textContent=sc+'%';$('#speechScoreRing').style.background=`conic-gradient(#159469 ${sc}%,#e8ecec ${sc}%)`;speechScores.push(sc);if(sc>=80){speechCorrect++;$('#speechFeedback').textContent='ممتاز جدًا!';$('#speechFeedbackText').textContent='التقط النظام الكلمة بشكل قريب جدًا من الهدف.';speak('ممتاز جدا، أحسنت يا بطل')}else if(sc>=55){$('#speechFeedback').textContent='جيد، حاول مرة أخرى';$('#speechFeedbackText').textContent='اقتربت من الكلمة. استمع للنموذج وكررها بهدوء.';speak('جيد، استمع للكلمة وحاول مرة أخرى')}else{$('#speechFeedback').textContent='نحتاج محاولة أخرى';$('#speechFeedbackText').textContent='استمع للنموذج، ثم انطق الكلمة ببطء ووضوح.';speak('حاول مرة أخرى ببطء ووضوح')}$('#nextSpeechBtn').classList.remove('hidden')};r.onerror=()=>toast('تعذر التقاط الصوت. تحقق من إذن الميكروفون.');r.onend=()=>$('#recordSpeechBtn').textContent='🎙️ ابدأ النطق';try{r.start()}catch{}};
$('#nextSpeechBtn').onclick=()=>{const set=SPEECH[speechSet];if(speechIndex<set.words.length-1){speechIndex++;renderSpeechWord();speak($('#speechTarget').textContent)}else finishSpeech()};
function finishSpeech(){const avg=Math.round(speechScores.reduce((a,b)=>a+b,0)/Math.max(1,speechScores.length));const pts=Math.round(avg/10)*5;const s={id:Date.now(),kind:'speech',activity:SPEECH[speechSet].title,speechSet,date:new Date().toISOString(),score:avg,points:pts,rating:null,note:'',words:SPEECH[speechSet].words,scores:speechScores};state.sessions.unshift(s);state.points+=pts;save();renderResult(s);route('result')}

function buildAssessment(){const mov=state.sessions.filter(s=>s.kind==='movement'),sp=state.sessions.filter(s=>s.kind==='speech');const skills=[];['balance','pearl','sail'].forEach(g=>{const a=mov.filter(s=>s.game===g);if(a.length){skills.push({name:GAMES[g].title,score:Math.round(a.reduce((x,s)=>x+s.score,0)/a.length),kind:'movement',game:g})}});if(sp.length)skills.push({name:'النطق واللغة',score:Math.round(sp.reduce((x,s)=>x+s.score,0)/sp.length),kind:'speech'});const total=skills.length?Math.round(skills.reduce((x,s)=>x+s.score,0)/skills.length):0;return {skills,total}}
function renderAssessment(){const a=buildAssessment();$('#assessmentScore').textContent=a.total;if(!a.skills.length){$('#assessmentLevel').textContent='لا توجد بيانات كافية بعد';$('#assessmentSummary').textContent='ابدأ جلسات الحركة أو النطق ليتمكن النظام من تحليل التقدم.';$('#masteredSkills').innerHTML='<div class="empty-state">لا توجد بيانات بعد.</div>';$('#weakSkills').innerHTML='<div class="empty-state">لا توجد بيانات بعد.</div>';$('#recommendationsList').innerHTML='<div class="empty-state">ستظهر التوصيات بعد تسجيل بعض الجلسات.</div>';return}$('#assessmentLevel').textContent=a.total>=80?'تقدم قوي':a.total>=60?'تقدم جيد مع مهارات تحتاج دعمًا':'نحتاج مزيدًا من التدريب التدريجي';$('#assessmentSummary').textContent=`المؤشر العام الحالي ${a.total}% بناءً على ${state.sessions.length} جلسة محفوظة.`;const good=a.skills.filter(x=>x.score>=75),weak=a.skills.filter(x=>x.score<75);$('#masteredSkills').innerHTML=good.length?good.map(x=>`<div class="skill-item good"><span>${x.name}</span><b>${x.score}%</b></div>`).join(''):'<div class="empty-state">لا توجد مهارة وصلت إلى مستوى الإتقان بعد.</div>';$('#weakSkills').innerHTML=weak.length?weak.map(x=>`<div class="skill-item weak"><span>${x.name}</span><b>${x.score}%</b></div>`).join(''):'<div class="empty-state">لا توجد مهارات منخفضة حاليًا.</div>';const rec=[];weak.forEach(x=>{if(x.kind==='speech')rec.push(['🗣️','النطق واللغة','كرر جلسة قصيرة من 4 كلمات، مع الاستماع للنموذج قبل كل محاولة وتقليل الضوضاء المحيطة.']);else if(x.game==='balance')rec.push(['⚖️','التوازن','استخدم جولات أقل ومدة ثبات أقصر، ثم ارفع الصعوبة تدريجيًا بعد نجاح متكرر.']);else if(x.game==='pearl')rec.push(['🦪','الوصول والانحناء','استخدم هدفًا أعلى في البداية لتقليل الانحناء، ثم اخفضه تدريجيًا ضمن النطاق المريح.']);else rec.push(['⛵','رفع الذراعين','ابدأ برفع اليدين إلى مستوى الكتفين، ثم زد الارتفاع تدريجيًا عند سهولة المهمة.'])});if(!rec.length)rec.push(['🌟','استمرار التقدم','حافظ على جلسات قصيرة ومتنوعة دون زيادة مفاجئة في الصعوبة.']);$('#recommendationsList').innerHTML=rec.map(r=>`<div class="recommendation-item"><span>${r[0]}</span><div><b>${r[1]}</b><p>${r[2]}</p></div></div>`).join('')}
$('#refreshAssessmentBtn').onclick=()=>{renderAssessment();toast('تم تحديث التحليل')};
function renderReports(){const all=state.sessions,m=all.filter(s=>s.kind==='movement'),sp=all.filter(s=>s.kind==='speech');$('#kpiSessions').textContent=all.length;$('#kpiMovement').textContent=m.length;$('#kpiSpeech').textContent=sp.length;$('#kpiPoints').textContent=state.points;const last=all.slice(0,8).reverse();$('#barChart').innerHTML=last.length?last.map((s,i)=>`<div class="bar" style="height:${Math.max(22,s.score*1.8)}px"><b>${s.score}%</b><span>${i+1}</span></div>`).join(''):'<div class="empty-state">لا توجد بيانات بعد.</div>';$('#sessionsBody').innerHTML=all.length?all.slice(0,15).map(s=>`<tr><td>${s.kind==='speech'?'نطق':'حركة'}</td><td>${s.activity}</td><td>${new Date(s.date).toLocaleDateString('ar-JO')}</td><td>${s.score}%</td><td>${s.rating?`${s.rating}/5`:'—'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-cell">لا توجد جلسات محفوظة.</td></tr>'}
$('#exportReportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({profile:state.profile,assessment:buildAssessment(),sessions:state.sessions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='farjan-report.json';a.click();URL.revokeObjectURL(a.href)};
function renderTherapist(){const p=state.profile||{};$('#therapistChildName').textContent=p.name||'الطفل';$('#tName').textContent=p.name||'—';$('#tMeta').textContent=p.age?`${p.age} سنوات • مستوى ${p.level}`:'—';$('#tGoal').textContent=goalLabel(p.goal);$('#planGame').value=state.plan.game;$('#planRounds').value=state.plan.rounds;$('#planHold').value=state.plan.hold;$('#planRoundsValue').textContent=state.plan.rounds;$('#planHoldValue').textContent=state.plan.hold;$('#planNote').value=state.plan.note||'';$('#therapistSessions').innerHTML=state.sessions.length?state.sessions.slice(0,6).map(s=>`<div class="mini-session"><div><b>${s.activity}</b><small>${new Date(s.date).toLocaleDateString('ar-JO')}</small></div><span>${s.kind==='speech'?'نطق':'حركة'}</span><b>${s.score}%</b></div>`).join(''):'<div class="empty-state">لا توجد جلسات بعد.</div>'}
$('#planRounds').oninput=e=>$('#planRoundsValue').textContent=e.target.value;$('#planHold').oninput=e=>$('#planHoldValue').textContent=e.target.value;$('#savePlanBtn').onclick=()=>{state.plan={game:$('#planGame').value,rounds:+$('#planRounds').value,hold:+$('#planHold').value,note:$('#planNote').value.trim()};save();$('#planSaveMsg').textContent='تم حفظ الخطة بنجاح.';speak('تم حفظ الخطة بنجاح');setTimeout(()=>$('#planSaveMsg').textContent='',1800)};
bindRoutes();if(state.profile){$('#childName').value=state.profile.name||'';$('#childAge').value=state.profile.age||'';$('#childGoal').value=state.profile.goal||'general';$('#childLevel').value=state.profile.level||'1'}syncVoice();window.addEventListener('beforeunload',stopCamera);
