const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const on=(sel,event,handler)=>{const el=typeof sel==='string'?$(sel):sel;if(el)el.addEventListener(event,handler);return el};
const KEY='farjan_final_state_v5';
const defaults={profile:null,points:0,sessions:[],plan:{game:'balance',rounds:5,hold:3,note:''},settings:{voice:true,dialect:'ar-QA'},speechProgress:{1:0,2:0,3:0,4:0,5:0,6:0}};
let state=load(), activeGame='balance', camera=null, pose=null, cameraActive=false, paused=false, demoMode=false, holdStart=null, roundLocked=false, rounds=0, score=0, startTime=0, timer=null, lastResultId=null, selectedRating=0;
let activeSpeechLevel=1,speechIndex=0,speechScores=[],speechAttempts=[],recognitionBusy=false,currentRecognition=null,lastSpeechScore=0;
const GAMES={balance:{title:'الحجلة الخليجية',type:'التوازن',icon:'⚖️',mission:'ارفع قدمًا واحدة',desc:'حافظ على توازنك لمدة {hold} ثوانٍ.',rounds:5,hold:3,m1:'زاوية الركبة اليسرى',m2:'زاوية الركبة اليمنى'},pearl:{title:'جمع اللؤلؤ',type:'الوصول والانحناء',icon:'🦪',mission:'اجمع اللؤلؤ',desc:'انحنِ تدريجيًا ومد يدك للأسفل.',rounds:6,hold:1.2,m1:'متوسط زاوية الركبتين',m2:'اليد للأسفل'},sail:{title:'رفع الشراع',type:'حركة الذراعين',icon:'⛵',mission:'ارفع الشراع',desc:'ارفع كلتا اليدين فوق الكتفين وثبّت الوضعية.',rounds:5,hold:2,m1:'اليد اليسرى فوق الكتف',m2:'اليد اليمنى فوق الكتف'}};
const MAKHRAJ={'ب':'أغلق الشفتين تمامًا ثم افتحهما بخفة مع خروج الصوت.','م':'أغلق الشفتين واجعل الصوت يمر مع رنين خفيف من الأنف.','ف':'ضع الشفة السفلى بخفة على أطراف الأسنان العليا ثم مرّر الهواء.','ت':'ضع طرف اللسان خلف الأسنان العليا مباشرة ثم حرّره سريعًا.','د':'ضع طرف اللسان خلف الأسنان العليا مع صوت أقوى قليلًا من التاء.','ن':'يلامس طرف اللسان خلف الأسنان العليا مع مرور جزء من الصوت من الأنف.','ل':'ضع طرف اللسان خلف الأسنان العليا واترك الهواء يمر من الجانبين.','س':'قرّب مقدمة اللسان من الأسنان دون لمسها ومرّر الهواء بصوت مستمر.','ش':'ارفع وسط اللسان قليلًا ومرّر الهواء بصوت الشين الواضح.','ر':'المس بطرف اللسان المنطقة خلف الأسنان العليا لمسة خفيفة وسريعة.','ك':'ارفع مؤخرة اللسان نحو سقف الحلق ثم حرّرها.','ق':'ارفع أقصى اللسان نحو الحنك الخلفي ثم أخرج الصوت بوضوح.'};
function sound(target,example,picture,letter,aliases){return{kind:'sound',target,example,picture,letter,makhraj:MAKHRAJ[letter],aliases,speak:`${target} ... ${example}`}}
function word(target,picture,aliases){return{kind:'word',target,example:`قل: ${target}`,picture,letter:target[0],makhraj:'انطق الكلمة بهدوء، وركز على أول صوت ثم أكمل بقية الكلمة.',aliases,speak:target}}
function sentence(target,picture,aliases){return{kind:'sentence',target,example:'جملة قصيرة',picture,letter:'',makhraj:'خذ نفسًا هادئًا، ثم قل الجملة كاملة بسرعة طبيعية ووضوح.',aliases,speak:target}}
const SPEECH_LEVELS=[
{id:1,title:'الحروف الشفوية مع الحركات',desc:'ابدأ بأصوات واضحة تعتمد على الشفتين.',visuals:'بَ  مِ  فُ',items:[sound('بَ','بَطَّة','🦆','ب',['بطة','بطه','باء','ب']),sound('بُ','بُرْج','🏰','ب',['برج','باء','ب']),sound('بِ','بِنْت','👧','ب',['بنت','باء','ب']),sound('مَ','مَاء','💧','م',['ماء','ما','ميم','م']),sound('مُ','مُوز','🍌','م',['موز','ميم','م']),sound('مِ','مِفْتاح','🔑','م',['مفتاح','ميم','م']),sound('فَ','فَراشَة','🦋','ف',['فراشة','فراشه','فاء','ف']),sound('فُ','فُسْتان','👗','ف',['فستان','فاء','ف']),sound('فِ','فِيل','🐘','ف',['فيل','فاء','ف'])]},
{id:2,title:'الحروف الأمامية مع الحركات',desc:'ننتقل إلى طرف اللسان والأسنان.',visuals:'تَ  دُ  نِ  لَ',items:[sound('تَ','تَمْر','🌴','ت',['تمر','تاء','ت']),sound('تُ','تُفّاح','🍎','ت',['تفاح','تاء','ت']),sound('تِ','تِين','🍈','ت',['تين','تاء','ت']),sound('دَ','دَجاجَة','🐔','د',['دجاجة','دجاجه','دال','د']),sound('دُ','دُمْيَة','🧸','د',['دمية','دميه','دال','د']),sound('دِ','دِيك','🐓','د',['ديك','دال','د']),sound('نَ','نَحْلَة','🐝','ن',['نحلة','نحله','نون','ن']),sound('نُ','نُجوم','⭐','ن',['نجوم','نون','ن']),sound('نِ','نِمْر','🐯','ن',['نمر','نون','ن']),sound('لَ','لَبَن','🥛','ل',['لبن','لام','ل']),sound('لُ','لُعْبَة','🪀','ل',['لعبة','لعبه','لام','ل']),sound('لِ','لِسان','👅','ل',['لسان','لام','ل'])]},
{id:3,title:'أصوات تحتاج دقة أكبر',desc:'تمييز أصوات متقاربة وأصوات من مؤخرة الفم.',visuals:'سَ  شُ  رِ  قَ',items:[sound('سَ','سَمَك','🐟','س',['سمك','سين','س']),sound('سُ','سُوق','🏪','س',['سوق','سين','س']),sound('سِ','سِوار','💍','س',['سوار','سين','س']),sound('شَ','شَمْس','☀️','ش',['شمس','شين','ش']),sound('شُ','شُراع','⛵','ش',['شراع','شين','ش']),sound('شِ','شِباك','🪟','ش',['شباك','شين','ش']),sound('رَ','رَمْل','🏖️','ر',['رمل','راء','ر']),sound('رُ','رُمّان','🍎','ر',['رمان','راء','ر']),sound('رِ','رِيشَة','🪶','ر',['ريشة','ريشه','راء','ر']),sound('كَ','كَرَة','⚽','ك',['كرة','كره','كاف','ك']),sound('قَ','قَطَر','🇶🇦','ق',['قطر','قاف','ق'])]},
{id:4,title:'مقاطع وكلمات بسيطة',desc:'نركّب الأصوات في كلمات قصيرة واضحة.',visuals:'باب  ماء  سمك',items:[word('باب','🚪',['باب']),word('ماء','💧',['ماء','ما']),word('فم','👄',['فم']),word('سمك','🐟',['سمك']),word('شمس','☀️',['شمس']),word('لعب','🪀',['لعب']),word('رمل','🏖️',['رمل']),word('قمر','🌙',['قمر'])]},
{id:5,title:'كلمات من التراث القطري والخليجي',desc:'مفردات قريبة من عالم الطفل داخل المنصة.',visuals:'بحر  لؤلؤ  شراع',items:[word('بحر','🌊',['بحر']),word('لؤلؤ','🦪',['لؤلؤ','لولو','اللؤلؤ']),word('شراع','⛵',['شراع']),word('نخلة','🌴',['نخلة','نخله']),word('سوق','🏪',['سوق']),word('فريج','🏘️',['فريج','الفريج']),word('قطر','🇶🇦',['قطر']),word('مركب','🛶',['مركب'])]},
{id:6,title:'جمل قصيرة',desc:'آخر مستوى: كلمات في جملة قصيرة.',visuals:'أنا أحب قطر',items:[sentence('أنا أحب قطر','🇶🇦',['انا احب قطر']),sentence('هذا مركب جميل','⛵',['هذا مركب جميل']),sentence('في الفريج نخلة','🌴',['في الفريج نخلة','في الفريج نخله']),sentence('أنا ألعب مع أصدقائي','🧒🏻',['انا العب مع اصدقائي'])]}
];
function cloneDefaults(){return JSON.parse(JSON.stringify(defaults))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{...cloneDefaults(),...x,plan:{...defaults.plan,...(x.plan||{})},settings:{...defaults.settings,...(x.settings||{})},speechProgress:{...defaults.speechProgress,...(x.speechProgress||{})}}}catch{return cloneDefaults()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setText(sel,t){const e=$(sel);if(e)e.textContent=t}
function route(n){$$('.page').forEach(p=>p.classList.remove('active'));const p=$('#page-'+n);if(!p)return;p.classList.add('active');try{window.scrollTo(0,0)}catch{};if(n==='dashboard')renderDashboard();if(n==='speech')renderSpeechLevels();if(n==='games')renderPoints();if(n==='reports')renderReports();if(n==='therapist')renderTherapist();syncVoice()}
function bindRoutes(){$$('[data-route]').forEach(b=>on(b,'click',e=>{e.preventDefault();const n=b.dataset.route;if(['dashboard','reports','therapist'].includes(n)&&!state.profile){route('onboarding');toast('أنشئ ملف الطفل أولًا');return}route(n)}));$$('[data-scroll]').forEach(b=>on(b,'click',()=>{$('#'+b.dataset.scroll)?.scrollIntoView({behavior:'smooth'});$('#topnav')?.classList.remove('open')}))}
function chooseArabicVoice(preferred='ar-QA'){const voices=window.speechSynthesis?.getVoices?.()||[],order=[preferred,'ar-QA','ar-AE','ar-SA','ar-KW','ar-BH','ar-OM','ar'];for(const lang of order){const exact=voices.find(v=>v.lang?.toLowerCase()===lang.toLowerCase());if(exact)return exact;const partial=voices.find(v=>v.lang?.toLowerCase().startsWith(lang.toLowerCase()));if(partial)return partial}return voices.find(v=>v.lang?.toLowerCase().startsWith('ar'))||null}
function speak(text,{slow=false,rate=null}={}){if(!state.settings.voice||!('speechSynthesis'in window)||!text)return Promise.resolve();return new Promise(resolve=>{try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),lang=state.settings.dialect||'ar-QA';u.lang=lang;u.rate=rate??(slow?.68:.92);u.pitch=1.03;u.volume=1;const v=chooseArabicVoice(lang);if(v)u.voice=v;u.onend=resolve;u.onerror=resolve;setTimeout(()=>speechSynthesis.speak(u),80)}catch{resolve()}})}
function gulfPraise(sc){if(sc>=90)return['كفو يا بطل! ممتاز جدًا','يا سلام عليك! هذي هي','عفية عليك، نطق حلو وواضح'][Math.floor(Math.random()*3)];if(sc>=72)return['زين يا بطل، ممتاز','حلو! قربت منها مضبوط','كفو، خلّنا نكمل'][Math.floor(Math.random()*3)];if(sc>=50)return['قريب يا بطل، خلّنا نعيدها بهدوء','زين، اسمعها مرة ثانية وجرّب','ما عليه، شوي شوي وبتضبط'][Math.floor(Math.random()*3)];return['ولا يهمك يا بطل، جرّب مرة ثانية','خلّنا نسمعها ببطء وبعدين نعيد','ما عليه، خذ وقتك وقلها بهدوء'][Math.floor(Math.random()*3)]}
function syncVoice(){const e=$('#voiceToggleBtn');if(e)e.textContent=state.settings.voice?'🔊 مفعّل':'🔇 متوقف'}
function toggleVoice(){state.settings.voice=!state.settings.voice;save();syncVoice();toast(state.settings.voice?'تم تفعيل التعزيز الصوتي':'تم إيقاف التعزيز الصوتي');if(state.settings.voice)speak('تم تفعيل الصوت يا بطل')}
on('#menuBtn','click',()=>$('#topnav')?.classList.toggle('open'));
on('#voiceToggleBtn','click',toggleVoice);
on('#childForm','submit',e=>{e.preventDefault();state.profile={name:$('#childName')?.value.trim()||'الطفل',age:$('#childAge')?.value||'',goal:$('#childGoal')?.value||'general',level:$('#childLevel')?.value||'1',created:new Date().toISOString()};save();route('dashboard');speak(`هلا ${state.profile.name}، جاهز نبدأ المغامرة؟`)});
function renderPoints(){['dashboardPoints','gamesPoints'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=state.points})}
function renderDashboard(){renderPoints();const p=state.profile||{};setText('#welcomeName',p.name?`هلا ${p.name} 👋`:'هلا يا بطل 👋');setText('#todayMission',p.goal==='speech'?'ابدأ بالمستوى المناسب في النطق':`مهمتك: ${GAMES[state.plan.game]?.title||'جلسة قصيرة'}`);setText('#sessionCountMini',state.sessions.length?`${state.sessions.length} جلسة مسجلة`:'لا جلسات بعد');setText('#planNoteView',state.plan.note||'اختر نشاطًا قصيرًا وكرر المحاولة بهدوء.')}
function levelUnlocked(level){if(level===1)return true;return(state.speechProgress[level-1]||0)>=65}
function renderSpeechLevels(){const box=$('#speechLevels');if(!box)return;if($('#speechDialect'))$('#speechDialect').value=state.settings.dialect||'ar-QA';box.innerHTML=SPEECH_LEVELS.map(l=>{const unlocked=levelUnlocked(l.id),pr=state.speechProgress[l.id]||0;return`<article class="level-card ${unlocked?'unlocked':'locked'}"><span class="level-no">المستوى ${l.id}</span>${unlocked?'':'<span class="lock-badge">🔒</span>'}<div class="level-visuals">${l.visuals}</div><h3>${l.title}</h3><p>${l.desc}</p><div class="level-progress"><i style="width:${pr}%"></i></div><small>${pr?`أفضل نتيجة ${pr}%`:unlocked?'جاهز للبدء':'يفتح بعد 65% في المستوى السابق'}</small><button class="${unlocked?'primary':'ghost'} full speech-level-start" data-level="${l.id}" ${unlocked?'':'disabled'}>${unlocked?'ابدأ المستوى':'مغلق'}</button></article>`}).join('');$$('.speech-level-start',box).forEach(b=>on(b,'click',()=>startSpeechLevel(+b.dataset.level)))}
on('#speechDialect','change',e=>{state.settings.dialect=e.target.value;save();toast('تم تغيير إعداد التقاط الصوت')});
function startSpeechLevel(level){activeSpeechLevel=level;speechIndex=0;speechScores=[];speechAttempts=[];route('speechplay');renderSpeechItem();setTimeout(()=>speak(currentSpeechItem().speak,{slow:true}),300)}
function currentSpeechLevel(){return SPEECH_LEVELS.find(x=>x.id===activeSpeechLevel)||SPEECH_LEVELS[0]}
function currentSpeechItem(){return currentSpeechLevel().items[speechIndex]}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function visualSvg(it){const target=esc(it.target),example=esc(it.example.replace(/^قل:\s*/,''));return`<svg viewBox="0 0 220 170" class="speech-svg" role="img" aria-label="${example}"><defs><linearGradient id="pv${speechIndex}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff8ea"/><stop offset="1" stop-color="#e5f4f5"/></linearGradient></defs><rect x="4" y="4" width="212" height="162" rx="28" fill="url(#pv${speechIndex})" stroke="#eadfce"/><circle cx="63" cy="72" r="42" fill="#fff" opacity=".9"/><text x="63" y="90" text-anchor="middle" font-size="54">${it.picture}</text><text x="151" y="72" text-anchor="middle" font-family="Tajawal,Arial" font-size="40" font-weight="900" fill="#7a1736">${target}</text><text x="151" y="111" text-anchor="middle" font-family="Tajawal,Arial" font-size="18" font-weight="700" fill="#49616b">${example}</text><circle cx="190" cy="26" r="8" fill="#d8a656" opacity=".8"/><circle cx="204" cy="38" r="4" fill="#168b8d" opacity=".8"/></svg>`}
function setSpeechScore(sc){lastSpeechScore=Math.max(0,Math.min(100,Math.round(sc||0)));setText('#speechScore',lastSpeechScore+'%');if($('#speechScoreRing'))$('#speechScoreRing').style.background=`conic-gradient(#159469 ${lastSpeechScore}%,#e8ecec ${lastSpeechScore}%)`}
function renderSpeechItem(){const level=currentSpeechLevel(),it=currentSpeechItem();setText('#speechLevelChip',`المستوى ${level.id}`);setText('#speechRound',`${speechIndex+1} / ${level.items.length}`);if($('#speechPicture'))$('#speechPicture').innerHTML=visualSvg(it);setText('#speechTarget',it.target);setText('#speechExample',it.kind==='sound'?`مثل: ${it.example}`:it.example);setText('#speechMakhraj',it.makhraj);setText('#speechPrompt',it.kind==='sound'?'اسمع الصوت والكلمة، ثم قل الصوت والكلمة معًا.':it.kind==='sentence'?'اسمع الجملة، ثم قلها كاملة.':'اسمع الكلمة ثم قلها بوضوح.');setText('#heardText','—');setText('#recognitionLang','سيظهر هنا إعداد الالتقاط المستخدم');setSpeechScore(0);setText('#speechFeedback','جاهز؟');setText('#speechFeedbackText','اسمع النموذج أولًا، ثم اضغط ابدأ النطق.');if($('#speechProgressBar'))$('#speechProgressBar').style.width=`${speechIndex/level.items.length*100}%`;['#retrySpeechBtn','#nextSpeechBtn','#parentConfirmSpeechBtn'].forEach(x=>$(x)?.classList.add('hidden'));const rb=$('#recordSpeechBtn');if(rb){rb.disabled=false;rb.textContent='🎙️ ابدأ النطق'}}
on('#listenTargetBtn','click',()=>speak(currentSpeechItem().speak));
on('#slowTargetBtn','click',()=>speak(currentSpeechItem().speak,{slow:true}));
on('#makhrajVoiceBtn','click',()=>speak(currentSpeechItem().makhraj,{slow:true,rate:.78}));
on('#retrySpeechBtn','click',()=>{renderSpeechItem();setTimeout(()=>startRecognition(),180)});
on('#nextSpeechBtn','click',()=>nextSpeechItem());
on('#parentConfirmSpeechBtn','click',()=>{const sc=Math.max(lastSpeechScore,70);setSpeechScore(sc);speechScores.push(sc);speechAttempts.push({target:currentSpeechItem().target,score:sc,parentConfirmed:true});speak('كفو، تم تأكيد المحاولة');showSpeechNext(true)});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function normalizeArabic(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/[^\u0621-\u064A ]/g,'').replace(/\s+/g,' ').trim()}
function lev(a,b){a=normalizeArabic(a);b=normalizeArabic(b);const m=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)m[i][0]=i;for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]}
function textSimilarity(a,b){const aa=normalizeArabic(a),bb=normalizeArabic(b);if(!aa||!bb)return 0;if(aa===bb)return 100;if(aa.includes(bb)||bb.includes(aa))return 92;let sc=Math.round((1-lev(aa,bb)/Math.max(aa.length,bb.length))*100);const at=new Set(aa.split(' ')),bt=new Set(bb.split(' ')),inter=[...at].filter(x=>bt.has(x)).length,uni=new Set([...at,...bt]).size;if(uni)sc=Math.max(sc,Math.round(inter/uni*100));return Math.max(0,sc)}
function scoreTranscript(transcript,confidence,it){const aliases=[it.target,it.example.replace(/^قل:\s*/,''),...(it.aliases||[])];let best=0;for(const a of aliases)best=Math.max(best,textSimilarity(transcript,a));const cb=Number.isFinite(confidence)?Math.round(confidence*10):0;if(it.kind==='sound'){const tr=normalizeArabic(transcript),first=normalizeArabic(it.letter);if(tr.startsWith(first)||tr.includes(first))best=Math.max(best,60)}return Math.min(100,Math.round(best*.92+cb))}
function langSequence(){const selected=$('#speechDialect')?.value||state.settings.dialect||'ar-QA';return[...new Set([selected,'ar-QA','ar-AE','ar-SA'])]}
function startRecognition(){if(recognitionBusy)return;if(!SpeechRecognition){toast('التعرف الصوتي غير متاح هنا. استخدم Chrome أو Edge، أو استعمل تأكيد ولي الأمر.');$('#parentConfirmSpeechBtn')?.classList.remove('hidden');return}if(window.speechSynthesis)try{speechSynthesis.cancel()}catch{};recognitionBusy=true;const rb=$('#recordSpeechBtn');if(rb){rb.disabled=true;rb.textContent='🎙️ أسمعك الآن...'}runRecognitionAttempt(langSequence(),0,[])}
function runRecognitionAttempt(langs,index,candidates){if(index>=langs.length){finishRecognition(candidates);return}const lang=langs[index];let r;try{r=new SpeechRecognition()}catch{finishRecognition(candidates);return}currentRecognition=r;r.lang=lang;r.interimResults=false;r.continuous=false;r.maxAlternatives=10;let got=false;r.onresult=e=>{got=true;const res=e.results?.[0];if(res)for(let i=0;i<res.length;i++){const alt=res[i];candidates.push({text:alt.transcript||'',confidence:Number(alt.confidence)||0,lang})}};r.onerror=e=>{if(!['no-speech','aborted'].includes(e.error))candidates.push({text:'',confidence:0,lang,error:e.error})};r.onend=()=>{if(got||candidates.some(x=>x.text))finishRecognition(candidates);else runRecognitionAttempt(langs,index+1,candidates)};try{r.start()}catch{runRecognitionAttempt(langs,index+1,candidates)}}
function finishRecognition(candidates){recognitionBusy=false;currentRecognition=null;const rb=$('#recordSpeechBtn');if(rb){rb.disabled=false;rb.textContent='🎙️ ابدأ النطق'}const it=currentSpeechItem(),usable=candidates.filter(c=>c.text.trim());if(!usable.length){setText('#heardText','لم ألتقط كلامًا واضحًا');setText('#recognitionLang','جرّب الاقتراب من الميكروفون أو اختر عربية واضحة');setSpeechScore(0);showSpeechFeedback(0);$('#retrySpeechBtn')?.classList.remove('hidden');$('#parentConfirmSpeechBtn')?.classList.remove('hidden');return}const scored=usable.map(c=>({...c,score:scoreTranscript(c.text,c.confidence,it)})).sort((a,b)=>b.score-a.score),best=scored[0];setText('#heardText',best.text);setText('#recognitionLang',`التقاط ${best.lang} • ${scored.length} احتمال`);setSpeechScore(best.score);speechScores.push(best.score);speechAttempts.push({target:it.target,heard:best.text,score:best.score,lang:best.lang,alternatives:scored.slice(0,4).map(x=>x.text)});showSpeechFeedback(best.score);const threshold=it.kind==='sound'?62:it.kind==='sentence'?72:68;if(best.score>=threshold)showSpeechNext(false);else{$('#retrySpeechBtn')?.classList.remove('hidden');$('#parentConfirmSpeechBtn')?.classList.remove('hidden')}}
function showSpeechFeedback(sc){const praise=gulfPraise(sc);setText('#speechFeedback',sc>=85?'ممتاز!':sc>=65?'زين جدًا!':sc>=45?'قريب يا بطل':'خلّنا نعيدها');setText('#speechFeedbackText',praise);speak(praise)}
function showSpeechNext(parentConfirmed){$('#nextSpeechBtn')?.classList.remove('hidden');if(!parentConfirmed)$('#retrySpeechBtn')?.classList.remove('hidden');if($('#speechProgressBar'))$('#speechProgressBar').style.width=`${(speechIndex+1)/currentSpeechLevel().items.length*100}%`}
function nextSpeechItem(){const l=currentSpeechLevel();if(speechIndex<l.items.length-1){speechIndex++;renderSpeechItem();setTimeout(()=>speak(currentSpeechItem().speak,{slow:true}),250)}else finishSpeechLevel()}
function finishSpeechLevel(){const avg=Math.round(speechScores.reduce((a,b)=>a+b,0)/Math.max(1,speechScores.length));state.speechProgress[activeSpeechLevel]=Math.max(state.speechProgress[activeSpeechLevel]||0,avg);const pts=Math.max(5,Math.round(avg/10)*5),l=currentSpeechLevel(),s={id:Date.now(),kind:'speech',activity:`المستوى ${l.id}: ${l.title}`,speechLevel:l.id,date:new Date().toISOString(),score:avg,points:pts,rating:null,note:'',attempts:speechAttempts};state.sessions.unshift(s);state.sessions=state.sessions.slice(0,60);state.points+=pts;save();renderResult(s);route('result');if(avg>=65&&activeSpeechLevel<SPEECH_LEVELS.length)speak(`كفو يا بطل، فتحت المستوى ${activeSpeechLevel+1}`);else speak(gulfPraise(avg))}
on('#recordSpeechBtn','click',startRecognition);
on('#micCheckBtn','click',async()=>{const box=$('#micStatus');box?.classList.remove('hidden');setText('#micStatusTitle','جاري فحص الميكروفون...');setText('#micStatusText','تكلم بصوت طبيعي لمدة 3 ثوانٍ.');if(!navigator.mediaDevices?.getUserMedia){setText('#micStatusTitle','الميكروفون غير متاح');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),AC=window.AudioContext||window.webkitAudioContext,ctx=new AC(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=512;src.connect(an);const data=new Uint8Array(an.fftSize);let peak=0,total=0,count=0,started=performance.now();await new Promise(resolve=>{const tick=()=>{an.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),pct=Math.min(100,Math.round(rms*420));peak=Math.max(peak,pct);total+=pct;count++;if($('#micMeter'))$('#micMeter').style.width=pct+'%';if(performance.now()-started<3000)requestAnimationFrame(tick);else resolve()};tick()});stream.getTracks().forEach(t=>t.stop());await ctx.close();const avg=Math.round(total/Math.max(1,count));setText('#micStatusTitle',peak<8?'الصوت منخفض جدًا':peak>92?'الصوت مرتفع جدًا':'الميكروفون جاهز ✓');setText('#micStatusText',peak<8?'قرّب الجهاز إلى 30–50 سم وتأكد من عدم كتم الميكروفون.':peak>92?'أبعد الجهاز قليلًا لتقليل التشويش.':`مستوى الصوت مناسب. متوسط الإشارة ${avg}%`)}catch{setText('#micStatusTitle','لم يتم السماح بالميكروفون');setText('#micStatusText','اسمح للمتصفح باستخدام الميكروفون ثم أعد الفحص.')}});
$$('.game-start').forEach(b=>on(b,'click',()=>startGame(b.dataset.game)));
function startGame(g){activeGame=g;rounds=0;score=0;holdStart=null;roundLocked=false;demoMode=false;paused=false;setupPlay();route('play');speak(`يلا يا بطل، بنبدأ ${GAMES[g].title}`)}
function setupPlay(){const c={...GAMES[activeGame]};if(state.plan.game===activeGame){c.rounds=+state.plan.rounds||c.rounds;c.hold=+state.plan.hold||c.hold}window.cfg=c;setText('#playGameType',c.type);setText('#playTitle',c.title);setText('#missionIcon',c.icon);setText('#missionTitle',c.mission);setText('#missionDesc',c.desc.replace('{hold}',c.hold));setText('#holdTargetLabel',` / ${c.hold.toFixed(1)} ثانية`);setText('#roundValue',`0 / ${c.rounds}`);setText('#playScore','0');setText('#metric1Label',c.m1);setText('#metric2Label',c.m2);setText('#metric1','—');setText('#metric2','—');setText('#trackingConfidence','—');setText('#detected','بانتظار الكاميرا');setText('#holdValue','0.0');if($('#holdProgress'))$('#holdProgress').style.width='0%';$('#cameraOverlay')?.classList.remove('hide');$('#simulateSuccessBtn')?.classList.add('hidden');setText('#sessionTimer','00:00');setText('#poseStatus','● الكاميرا متوقفة');clearInterval(timer)}
function angle(a,b,c){const ab={x:a.x-b.x,y:a.y-b.y},cb={x:c.x-b.x,y:c.y-b.y};const d=Math.hypot(ab.x,ab.y)*Math.hypot(cb.x,cb.y);if(!d)return 180;let co=(ab.x*cb.x+ab.y*cb.y)/d;co=Math.max(-1,Math.min(1,co));return Math.acos(co)*180/Math.PI}
function visible(l){return[0,11,12,23,24,25,26,27,28].every(i=>(l[i].visibility??1)>.45)}
function evalPose(l){let good=false,m1='—',m2='—';if(activeGame==='balance'){const a=angle(l[23],l[25],l[27]),b=angle(l[24],l[26],l[28]);m1=Math.round(a)+'°';m2=Math.round(b)+'°';good=(a<150&&b>158)||(b<150&&a>158)}else if(activeGame==='pearl'){const a=angle(l[23],l[25],l[27]),b=angle(l[24],l[26],l[28]),av=(a+b)/2,w=Math.min(l[15].y,l[16].y),h=(l[23].y+l[24].y)/2;m1=Math.round(av)+'°';m2=w>h?'نعم':'ليس بعد';good=av<145&&w>h}else{const le=l[15].y<l[11].y,ri=l[16].y<l[12].y;m1=le?'نعم ✓':'لا';m2=ri?'نعم ✓':'لا';good=le&&ri}setText('#metric1',m1);setText('#metric2',m2);return good}
function updateHold(g){if(paused)return;const c=window.cfg;if(g){if(!holdStart){holdStart=performance.now();speak('كفو، استمر')}const s=Math.min(c.hold,(performance.now()-holdStart)/1000);setText('#holdValue',s.toFixed(1));if($('#holdProgress'))$('#holdProgress').style.width=(s/c.hold*100)+'%';setText('#feedbackBubble',s<c.hold?'زين، حافظ على الوضع':'كفو يا بطل!');if(s>=c.hold&&!roundLocked)scoreRound()}else if(!roundLocked){holdStart=null;setText('#holdValue','0.0');if($('#holdProgress'))$('#holdProgress').style.width='0%';setText('#feedbackBubble',activeGame==='balance'?'ارفع قدمًا واحدة':activeGame==='pearl'?'انحنِ ومد يدك للأسفل':'ارفع اليدين فوق الكتفين')}}
function scoreRound(){roundLocked=true;rounds++;score+=10;setText('#roundValue',`${rounds} / ${window.cfg.rounds}`);setText('#playScore',score);speak(rounds>=window.cfg.rounds?'يا سلام عليك، خلصت التحدي':'كفو، الجولة اللي بعدها');if(rounds>=window.cfg.rounds)setTimeout(()=>finishMovement(false),650);else setTimeout(()=>{holdStart=null;roundLocked=false;setText('#holdValue','0.0');if($('#holdProgress'))$('#holdProgress').style.width='0%'},900)}
function initPose(){if(pose||typeof Pose==='undefined')return;pose=new Pose({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/pose/${f}`});pose.setOptions({modelComplexity:1,smoothLandmarks:true,minDetectionConfidence:.55,minTrackingConfidence:.55});pose.onResults(r=>{const v=$('#video'),c=$('#canvas');if(!v||!c)return;const x=c.getContext('2d');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;x.clearRect(0,0,c.width,c.height);if(r.poseLandmarks){const l=r.poseLandmarks;if(typeof drawConnectors==='function')drawConnectors(x,l,POSE_CONNECTIONS,{color:'#35d0a0',lineWidth:4});if(typeof drawLandmarks==='function')drawLandmarks(x,l,{color:'#ffd56a',radius:3});const ok=visible(l);setText('#detected',ok?'كامل ✓':'غير كامل');setText('#trackingConfidence',ok?'جيدة':'ضعيفة');setText('#poseStatus',ok?'● الجسم ظاهر':'● عدّل موقع الكاميرا');if(ok)updateHold(evalPose(l));else{setText('#feedbackBubble','ابتعد شوي ليظهر الجسم كاملًا');holdStart=null}}else setText('#detected','لم يتم الاكتشاف')})}
function beginTimer(){startTime=Date.now();clearInterval(timer);timer=setInterval(()=>setText('#sessionTimer',fmt(Math.round((Date.now()-startTime)/1000))),1000)}
on('#startCameraBtn','click',async()=>{try{if(typeof Camera==='undefined'||typeof Pose==='undefined')throw new Error('MediaPipe غير محمل');initPose();cameraActive=true;$('#cameraOverlay')?.classList.add('hide');const v=$('#video');camera=new Camera(v,{onFrame:async()=>{if(cameraActive&&!paused&&pose)await pose.send({image:v})},width:1280,height:720});await camera.start();beginTimer();speak('قف في النص وخلك ظاهر كامل قدام الكاميرا')}catch(e){console.error(e);toast('تعذر تشغيل الكاميرا. اسمح بالكاميرا أو استخدم وضع التجربة.')}});
on('#demoModeBtn','click',()=>{demoMode=true;cameraActive=false;$('#cameraOverlay')?.classList.add('hide');$('#simulateSuccessBtn')?.classList.remove('hidden');setText('#poseStatus','● وضع التجربة');beginTimer();toast('وضع التجربة جاهز')});
on('#simulateSuccessBtn','click',()=>{if(roundLocked)return;holdStart=performance.now()-window.cfg.hold*1000;updateHold(true)});
on('#pauseBtn','click',()=>{paused=!paused;setText('#pauseBtn',paused?'▶ متابعة':'⏸ إيقاف مؤقت');speak(paused?'وقفنا شوي':'يلا نكمل')});
on('#endGameBtn','click',()=>{if(confirm('إنهاء الجلسة الحالية؟'))finishMovement(true)});
function stopCamera(){cameraActive=false;if(camera){try{camera.stop()}catch{}camera=null}clearInterval(timer)}
function finishMovement(cancelled=false){stopCamera();const duration=startTime?Math.max(1,Math.round((Date.now()-startTime)/1000)):0;if(cancelled&&rounds===0){route('games');return}const target=window.cfg?.rounds||GAMES[activeGame].rounds,perf=Math.round(rounds/target*100),s={id:Date.now(),kind:'movement',game:activeGame,activity:GAMES[activeGame].title,date:new Date().toISOString(),duration,rounds,targetRounds:target,score:perf,points:score,rating:null,note:'',mode:demoMode?'demo':'camera'};state.sessions.unshift(s);state.sessions=state.sessions.slice(0,60);state.points+=score;save();renderResult(s);route('result')}
function fmt(sec){sec=Math.round(sec||0);const m=Math.floor(sec/60),s=sec%60;return m?`${m}:${String(s).padStart(2,'0')} د`:`${s} ث`}
function renderResult(s){lastResultId=s.id;selectedRating=s.rating||0;setText('#resultHeadline',`أحسنت ${state.profile?.name||'يا بطل'}!`);setText('#resultSubtitle',s.kind==='speech'?`نتيجة النطق في هذه الجلسة ${s.score}%`:`أكملت ${s.rounds}/${s.targetRounds} من المهام.`);const rs=$('#resultStats');if(rs)rs.innerHTML=s.kind==='speech'?[['🗣️ النتيجة',`${s.score}%`],['⭐ النقاط',`+${s.points}`],['🎯 المستوى',`${s.speechLevel}`]].map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b></article>`).join(''):[['⭐ النقاط',`+${s.points}`],['⏱ المدة',fmt(s.duration)],['🎯 المهام',`${s.rounds}/${s.targetRounds}`]].map(x=>`<article><small>${x[0]}</small><b>${x[1]}</b></article>`).join('');if($('#evalNote'))$('#evalNote').value=s.note||'';$$('.rate-btn').forEach(b=>b.classList.toggle('active',+b.dataset.rate===selectedRating))}
$$('.rate-btn').forEach(b=>on(b,'click',()=>{selectedRating=+b.dataset.rate;$$('.rate-btn').forEach(x=>x.classList.toggle('active',x===b));speak(gulfPraise(40+selectedRating*12))}));
on('#saveEvaluationBtn','click',()=>{const i=state.sessions.findIndex(s=>s.id===lastResultId);if(i<0)return;state.sessions[i].rating=selectedRating||null;state.sessions[i].note=$('#evalNote')?.value.trim()||'';save();setText('#evalSaveMsg','تم حفظ تقييم ولي الأمر.');toast('تم حفظ التقييم')});
function buildAssessment(){const mov=state.sessions.filter(s=>s.kind==='movement'),sp=state.sessions.filter(s=>s.kind==='speech'),skills=[];['balance','pearl','sail'].forEach(g=>{const a=mov.filter(s=>s.game===g);if(a.length)skills.push({name:GAMES[g].title,score:Math.round(a.reduce((x,s)=>x+s.score,0)/a.length),kind:'movement',game:g})});if(sp.length)skills.push({name:'النطق واللغة',score:Math.round(sp.reduce((x,s)=>x+s.score,0)/sp.length),kind:'speech'});const total=skills.length?Math.round(skills.reduce((x,s)=>x+s.score,0)/skills.length):0;return{skills,total}}
function weakestSpeechLevel(){const e=SPEECH_LEVELS.map(l=>({id:l.id,title:l.title,score:state.speechProgress[l.id]||0})).filter(x=>x.score>0);return e.sort((a,b)=>a.score-b.score)[0]||null}
function renderReports(){const all=state.sessions,m=all.filter(s=>s.kind==='movement'),sp=all.filter(s=>s.kind==='speech'),a=buildAssessment();setText('#kpiSessions',all.length);setText('#kpiMovement',m.length);setText('#kpiSpeech',sp.length);setText('#kpiPoints',state.points);setText('#assessmentScore',a.total);setText('#assessmentLevel',!a.skills.length?'لا توجد بيانات كافية بعد':a.total>=80?'تقدم قوي':a.total>=60?'تقدم جيد مع نقاط تحتاج دعم':'نحتاج تدريبًا تدريجيًا أكثر');setText('#assessmentSummary',!a.skills.length?'ابدأ جلسات الحركة أو النطق ليظهر التحليل.':`المؤشر العام الحالي ${a.total}% مبني على ${all.length} جلسة محفوظة.`);const good=a.skills.filter(x=>x.score>=75),weak=a.skills.filter(x=>x.score<75);if($('#masteredSkills'))$('#masteredSkills').innerHTML=good.length?good.map(x=>`<div class="skill-item good"><span>${x.name}</span><b>${x.score}%</b></div>`).join(''):'<div class="empty-state">لا توجد مهارة وصلت إلى الإتقان بعد.</div>';if($('#weakSkills'))$('#weakSkills').innerHTML=weak.length?weak.map(x=>`<div class="skill-item weak"><span>${x.name}</span><b>${x.score}%</b></div>`).join(''):'<div class="empty-state">لا توجد مهارات منخفضة حاليًا.</div>';const rec=[];weak.forEach(x=>{if(x.kind==='speech'){const lv=weakestSpeechLevel();rec.push(['🗣️','النطق واللغة',lv?`أعد المستوى ${lv.id} (${lv.title}) بجلسات قصيرة واستخدم «اسمع ببطء» قبل التسجيل.`:'كرر جلسة قصيرة في مكان هادئ مع النموذج البطيء.'])}else if(x.game==='balance')rec.push(['⚖️','التوازن','قلّل مدة الثبات والجولات ثم زدها تدريجيًا بعد نجاح متكرر.']);else if(x.game==='pearl')rec.push(['🦪','الوصول والانحناء','ابدأ بانحناء بسيط وهدف قريب ثم وسّع المدى تدريجيًا.']);else rec.push(['⛵','رفع الذراعين','ابدأ إلى مستوى الكتفين ثم زد الارتفاع تدريجيًا.'])});if(!rec.length&&a.skills.length)rec.push(['🌟','استمرار التقدم','حافظ على جلسات قصيرة ومتنوعة ولا ترفع الصعوبة دفعة واحدة.']);if($('#recommendationsList'))$('#recommendationsList').innerHTML=rec.length?rec.map(r=>`<div class="recommendation-item"><span>${r[0]}</span><div><b>${r[1]}</b><p>${r[2]}</p></div></div>`).join(''):'<div class="empty-state">ستظهر التوصيات بعد تسجيل الجلسات.</div>';if($('#sessionsBody'))$('#sessionsBody').innerHTML=all.length?all.slice(0,15).map(s=>`<tr><td>${s.kind==='speech'?'نطق':'حركة'}</td><td>${s.activity}</td><td>${new Date(s.date).toLocaleDateString('ar-JO')}</td><td>${s.score}%</td></tr>`).join(''):'<tr><td colspan="4" class="empty-cell">لا توجد جلسات محفوظة.</td></tr>'}
on('#exportReportBtn','click',()=>{const blob=new Blob([JSON.stringify({profile:state.profile,speechProgress:state.speechProgress,assessment:buildAssessment(),sessions:state.sessions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='farjan-report.json';a.click();URL.revokeObjectURL(a.href)});
function renderTherapist(){if($('#planGame'))$('#planGame').value=state.plan.game;if($('#planRounds'))$('#planRounds').value=state.plan.rounds;if($('#planHold'))$('#planHold').value=state.plan.hold;setText('#planRoundsValue',state.plan.rounds);setText('#planHoldValue',state.plan.hold);if($('#planNote'))$('#planNote').value=state.plan.note||''}
on('#planRounds','input',e=>setText('#planRoundsValue',e.target.value));on('#planHold','input',e=>setText('#planHoldValue',e.target.value));on('#savePlanBtn','click',()=>{state.plan={game:$('#planGame')?.value||'balance',rounds:+($('#planRounds')?.value||5),hold:+($('#planHold')?.value||3),note:$('#planNote')?.value.trim()||''};save();setText('#planSaveMsg','تم حفظ الخطة بنجاح.');speak('تم حفظ الخطة، يعطيكم العافية');setTimeout(()=>setText('#planSaveMsg',''),1800)});
bindRoutes();
if(state.profile){if($('#childName'))$('#childName').value=state.profile.name||'';if($('#childAge'))$('#childAge').value=state.profile.age||'';if($('#childGoal'))$('#childGoal').value=state.profile.goal||'general';if($('#childLevel'))$('#childLevel').value=state.profile.level||'1'}
if($('#speechDialect'))$('#speechDialect').value=state.settings.dialect||'ar-QA';syncVoice();window.speechSynthesis?.getVoices?.();window.addEventListener('beforeunload',()=>{stopCamera();try{currentRecognition?.abort()}catch{}});
